In [13]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('/Users/sreemalathi/Documents/appproject/Marketing Campaign analytics/Data/marketing_campaign.csv', sep=';')

In [14]:
df.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,2012-09-04,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,2014-03-08,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,2013-08-21,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,2014-02-10,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,2014-01-19,94,173,...,5,0,0,0,0,0,0,3,11,0

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   str
 3   Marital_Status       2240 non-null   str
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   str
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response             2240 non-null   int64
dtypes: float64(1), int64(25), str(3)
memory usage: 507.6 KB

# Duplicates

In [55]:
df.duplicated().sum()

np.int64(0)

In [56]:
df['ID'].duplicated().sum()

np.int64(0)

In [57]:
df.dtypes

ID                              int64
Year_Birth                      int64
Education                         str
Marital_Status                    str
Income                        float64
Kidhome                         int64
Teenhome                        int64
Dt_Customer            datetime64[us]
Recency                         int64
MntWines                        int64
MntFruits                       int64
MntMeatProducts                 int64
MntFishProducts                 int64
MntSweetProducts                int64
MntGoldProds                    int64
NumDealsPurchases               int64
NumWebPurchases                 int64
NumCatalogPurchases             int64
NumStorePurchases               int64
NumWebVisitsMonth               int64
AcceptedCmp3                    int64
AcceptedCmp4                    int64
AcceptedCmp5                    int64
AcceptedCmp1                    int64
AcceptedCmp2                    int64
Complain                        int64
Z_CostContact                   int64
Z_Revenue                       int64
Response                        int64
Age_Enrolled                    int64
dtype: object

# Income Column Analysis

In [ ]:
# Convert the 'Dt_Customer' column to datetime format
df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'])

In [6]:
df.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,2012-09-04,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,2014-03-08,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,2013-08-21,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,2014-02-10,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,2014-01-19,94,173,...,5,0,0,0,0,0,0,3,11,0

In [7]:
df.isnull().sum()

ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

In [8]:
df['Income'].describe()

count      2216.000000
mean      52247.251354
std       25173.076661
min        1730.000000
25%       35303.000000
50%       51381.500000
75%       68522.000000
max      666666.000000
Name: Income, dtype: float64

In [19]:
Q1 = 35303
Q3 = 68522
IQR = Q3 - Q1
IQR

33219

In [21]:
upper_limit = Q3 + 1.5 * IQR
lower_limit = Q1 - 1.5 * IQR

In [ ]:
(df['Income'] > upper_limit).sum()
# Number of rows where Income is greater than the upper limit
# only ID9432 seems to be an outlier with Income = 666666 too high compared to the rest of the data.

        ID    Income
2233  9432  666666.0
617   1503  162397.0
687   1501  160803.0
1300  5336  157733.0
164   8475  157243.0

In [22]:
(df['Income'] > lower_limit).sum()

np.int64(2216)

In [33]:
df.loc[df.isna().any(axis=1),:]

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
10,1994,1983,Graduation,Married,NaN,1,0,2013-11-15,11,5,...,7,0,0,0,0,0,0,3,11,0
27,5255,1986,Graduation,Single,NaN,1,0,2013-02-20,19,5,...,1,0,0,0,0,0,0,3,11,0
43,7281,1959,PhD,Single,NaN,0,0,2013-11-05,80,81,...,2,0,0,0,0,0,0,3,11,0
48,7244,1951,Graduation,Single,NaN,2,1,2014-01-01,96,48,...,6,0,0,0,0,0,0,3,11,0
58,8557,1982,Graduation,Single,NaN,1,0,2013-06-17,57,11,...,6,0,0,0,0,0,0,3,11,0
71,10629,1973,2n Cycle,Married,NaN,1,0,2012-09-14,25,25,...,8,0,0,0,0,0,0,3,11,0
90,8996,1957,PhD,Married,NaN,2,1,2012-11-19,4,230,...,9,0,0,0,0,0,0,3,11,0
91,9235,1957,Graduation,Single,NaN,1,1,2014-05-27,45,7,...,7,0,0,0,0,0,0,3,11,0
92,5798,1973,Master,Together,NaN,0,0,2013-11-23,87,445,...,1,0,0,0,0,0,0,3,11,0
128,8268,1961,PhD,Married,NaN,0,1,2013-07-11,23,352,...,6,0,0,0,0,0,0,3,11,0
133,1295,1963,Graduation,Married,NaN,0,1,2013-08-11,96,231,...,4,0,0,0,0,0,0,3,11,0
312,2437,1989,Graduation,Married,NaN,0,0,2013-06-03,69,861,...,3,0,1,0,1,0,0,3,11,0
319,2863,1970,Graduation,Single,NaN,1,2,2013-08-23,67,738,...,7,0,1,0,1,0,0,3,11,0
1379,10475,1970,Master,Together,NaN,0,1,2013-04-01,39,187,...,5,0,0,0,0,0,0,3,11,0
1382,2902,1958,Graduation,Together,NaN,1,1,2012-09-03,87,19,...,5,0,0,0,0,0,0,3,11,0
1383,4345,1964,2n Cycle,Single,NaN,1,1,2014-01-12,49,5,...,7,0,0,0,0,0,0,3,11,0
1386,3769,1972,PhD,Together,NaN,1,0,2014-03-02,17,25,...,7,0,0,0,0,0,0,3,11,0
2059,7187,1969,Master,Together,NaN,1,1,2013-05-18,52,375,...,3,0,0,0,0,0,0,3,11,0
2061,1612,1981,PhD,Single,NaN,1,0,2013-05-31,82,23,...,6,0,0,0,0,0,0,3,11,0
2078,5079,1971,Graduation,Married,NaN,1,1,2013-03-03,82,71,...,8,0,0,0,0,0,0,3,11,0
2079,10339,1954,Master,Together,NaN,0,1,2013-06-23,83,161,...,6,0,0,0,0,0,0,3,11,0
2081,3117,1955,Graduation,Single,NaN,0,1,2013-10-18,95,264,...,7,0,0,0,0,0,0,3,11,0
2084,5250,1943,Master,Widow,NaN,0,0,2013-10-30,75,532,...,1,0,0,1,0,0,0,3,11,1
2228,8720,1978,2n Cycle,Together,NaN,0,0,2012-08-12,53,32,...,0,0,1,0,0,0,0,3,11,0

In [ ]:
# Fill missing values in the Income column with the median value of the column
median_income = df['Income'].median()
df['Income'] = df['Income'].fillna(median_income)

In [ ]:
# replace the outlier value of 666666 with the median value of the Income column
df.loc[df['Income'] == 666666, 'Income'] = median_income

In [39]:
df['Income'].max()
df[df['ID'] == 9432][['ID', 'Income']]

        ID   Income
2233  9432  51381.5

# Year Column Analysis

In [40]:
df['Year_Birth'].describe()

count    2240.000000
mean     1968.805804
std        11.984069
min      1893.000000
25%      1959.000000
50%      1970.000000
75%      1977.000000
max      1996.000000
Name: Year_Birth, dtype: float64

In [ ]:
# Calculate the age of customers at the time of enrollment as Age_Enrolled Column
df['Age_Enrolled'] = df['Dt_Customer'].dt.year - df['Year_Birth']

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,Age_Enrolled
192,7829,1900,2n Cycle,Divorced,36640.0,1,0,2013-09-26,99,15,...,0,0,0,0,0,1,3,11,0,113
239,11004,1893,2n Cycle,Single,60182.0,0,1,2014-05-17,23,8,...,0,0,0,0,0,0,3,11,0,121
339,1150,1899,PhD,Together,83532.0,0,0,2013-09-26,36,755,...,0,0,1,0,0,0,3,11,0,114

In [47]:
df.loc[df['Age_Enrolled']>100,:]

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response,Age_Enrolled
192,7829,1900,2n Cycle,Divorced,36640.0,1,0,2013-09-26,99,15,...,0,0,0,0,0,1,3,11,0,113
239,11004,1893,2n Cycle,Single,60182.0,0,1,2014-05-17,23,8,...,0,0,0,0,0,0,3,11,0,121
339,1150,1899,PhD,Together,83532.0,0,0,2013-09-26,36,755,...,0,0,1,0,0,0,3,11,0,114

In [ ]:
# Replace outliers in 'Age_Enrolled' with the median 'Year_Birth'
median_birth = int(df['Year_Birth'].median())
df.loc[df['Age_Enrolled'] > 100, 'Year_Birth'] = median_birth
df['Age_Enrolled'] = df['Dt_Customer'].dt.year - df['Year_Birth']

In [51]:
df['Year_Birth'].min()
df['Age_Enrolled'].describe()
df.loc[df['ID'].isin([7829, 11004, 1150]), ['ID', 'Year_Birth', 'Age_Enrolled']]

        ID  Year_Birth  Age_Enrolled
192   7829        1970            43
239  11004        1970            44
339   1150        1970            43

In [50]:
df['Marital_Status'].value_counts()

Marital_Status
Married     864
Together    580
Single      480
Divorced    232
Widow        77
Alone         3
Absurd        2
YOLO          2
Name: count, dtype: int64

In [ ]:
# Filter the DataFrame to only include valid marital status values
valid_status = ['Married', 'Together', 'Single', 'Divorced', 'Widow']
df = df[df['Marital_Status'].isin(valid_status)].reset_index(drop=True)
df.shape

(2233, 30)

In [53]:
df['Education'].value_counts()

Education
Graduation    1125
PhD            483
Master         368
2n Cycle       203
Basic           54
Name: count, dtype: int64

In [54]:
df['Education'] = df['Education'].replace({
    '2n Cycle': 'Masters',
    'Master': 'Masters',
    'Graduation': 'Bachelors'
})
df['Education'].value_counts()

Education
Bachelors    1125
Masters       571
PhD           483
Basic          54
Name: count, dtype: int64

# Cleaned Data

In [ ]:
# Save the cleaned DataFrame to a new CSV file
df.to_csv('/Users/sreemalathi/Documents/appproject/Marketing Campaign analytics/Data/marketing_campaign_clean.csv', index=False)